### ISSUE TITLE
Site is is not generaing as of 3.6

### ISSUE THREAD

**Issue by emacarron** [mybatis/guice#21]
mvn site fails in 3.6 but worked in 3.5.

Looks like there is one wrong javadoc.

**Comment by christianpoitras** [comment]
@emacarron Did you solve this issue?

**Comment by emacarron** [comment]
Hi Christian. I made a change that worked. Not sure if it was the right one but anyway I think we can close this one.

**Comment by christianpoitras** [comment]
Thanks. I don't see a better alternative than findbugs jsr305. So we'll stick to your fix and update to a more recent version from google code if we need.

**Comment by christianpoitras** [comment]
@emacarron Seems bug is still valid with the fail in 3.7.

**Comment by emacarron** [comment]
Christian, I am afraid this is not exactly the same problem but something
related to the new site deployment method that Jeremy was exploring.

2015-07-28 15:18 GMT+02:00 Christian Poitras <notifications@github.com>:

**Comment by hazendaz** [comment]
For now possibly drop parent to the prior one and try the old site deploy.  Possible option anyway.  Issue I'm running into looks like it's caused by the site plugin itself...


Sent by Outlook for Android





On Tue, Jul 28, 2015 at 8:51 AM -0700, "Eduardo Macarron" <notifications@github.com> wrote:
Christian, I am afraid this is not exactly the same problem but something
related to the new site deployment method that Jeremy was exploring.

2015-07-28 15:18 GMT+02:00 Christian Poitras <notifications@github.com>:

> Reopened #21 <https://github.com/mybatis/guice/issues/21>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mybatis/guice/issues/21#event-367209892>.
>


---

**Comment by emacarron** [comment]
Jeremy. No worries. If needed the site can be generated by hand and pushed
to gh-pages.

**Comment by christianpoitras** [comment]
This issue is probably fixed for 3.8.

**Comment by hazendaz** [comment]
Thanks @christianpoitras.  This has been resolved.
