### ISSUE TITLE
in mybatis-config.xml, environments's [default] attribute doesn't work.

### ISSUE THREAD

**Issue by sandpie** [mybatis/guice#51]
version:3.7.1

in mybatis-config.xml, environments's [default] attribute doesn't work.

becuse in class XMLMyBatisModule,  environmentId has default value [development]，

**Comment by christianpoitras** [comment]
To fix this, XMLMyBatisModule must be updated with the following:

DEFAULT_ENVIRONMENT_ID should be null.
setEnvironmentId() must accept null.

**Comment by cgendreau** [comment]
Any reason why there is no default EnvironmentId available in MyBatisModule?

**Comment by christianpoitras** [comment]
This comes back to the first version of MyBatis-Guice that was Java only. Since no XML was available, it made no sense to not set an environment id. The default value was "development" if I remember correctly.

After, we decided to support XML configuration files since it the usual way to configure MyBatis. But we merely copied the Java configuration class and patched it to support XML. This led us to ignore the default environment id in the XML file.
