### ISSUE TITLE
Generic TypeHandlers not working with XML config.

### ISSUE THREAD

**Issue by GenghisZahn** [mybatis/guice#88]
My issue seems to be related to #82 and #30:

I'm using an XMLMyBatisModule setup with a generic TypeHandler to convert between Java objects and postgres Json data fields.  During initialization I get:

```
org.apache.ibatis.type.TypeException: Unable to find a usable constructor for class com.calverteducation.jvirgil.mybatisDao.typeHandler.JsonTypeHandler
  at org.mybatis.guice.XMLMyBatisModule.internalConfigure(XMLMyBatisModule.java:119)
```

Looking at the other issues, it seem like this problem may already be solved with a java-based configuration, but XML config is still a valid option (that I'm currently using) so the fix should work there as well.

**Comment by christianpoitras** [comment]
Do you have a test case for this?

**Comment by GenghisZahn** [comment]
I'm not sure I get your meaning. I have a test case in my project that can recreate the issue, but that's not helpful to you. Do you want me to create a test case within this project's test does and submit a pull request?

Either way, I've figured out the source of the error:

1. My TypeHandler class needed a `@MappedTypes(Object.class)` annotation
2. I had to explicitly register the typeHandler in my config.xml instead of just letting it get picked up with the rest of the package.

**Comment by christianpoitras** [comment]
The way XML configuration works is that MyBatis-Guice inject all dependencies in registered type handlers. But type handlers are registered by MyBatis and not MyBatis-Guice when using XML.

That is why I though that you had a problem in your configuration. If you do need injection in your type handler, remember that only setter/field injection works since the type handler cannot instantiated.
